version: '3.8'

services:
  app:
    container_name: webhook-app
    platform: linux/arm64
    build: 
      context: .
      args:
        PORT: ${PORT:-3000}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file: .env
    environment:
      - PORT=${PORT:-3000}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
